// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview Recommends products to users based on their viewing history.
 *
 * - getProductRecommendations - A function that returns product recommendations.
 * - GetProductRecommendationsInput - The input type for the getProductRecommendations function.
 * - GetProductRecommendationsOutput - The return type for the getProductRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetProductRecommendationsInputSchema = z.object({
  viewingHistory: z.array(
    z.string().describe('The product IDs the user has viewed.')
  ).describe('The user viewing history as an array of product IDs.'),
});
export type GetProductRecommendationsInput = z.infer<typeof GetProductRecommendationsInputSchema>;

const GetProductRecommendationsOutputSchema = z.object({
  recommendedProducts: z.array(
    z.string().describe('The product IDs of the recommended products.')
  ).describe('The product recommendations based on the viewing history.'),
});
export type GetProductRecommendationsOutput = z.infer<typeof GetProductRecommendationsOutputSchema>;

export async function getProductRecommendations(input: GetProductRecommendationsInput): Promise<GetProductRecommendationsOutput> {
  return productRecommendationsFlow(input);
}

const productRecommendationsPrompt = ai.definePrompt({
  name: 'productRecommendationsPrompt',
  input: {schema: GetProductRecommendationsInputSchema},
  output: {schema: GetProductRecommendationsOutputSchema},
  prompt: `You are a product recommendation engine for an e-commerce website.

  Based on the user's viewing history, recommend products that they might be interested in. Only return a list of product IDs.

  Viewing History: {{viewingHistory}}

  Recommendations:`,
});

const productRecommendationsFlow = ai.defineFlow(
  {
    name: 'productRecommendationsFlow',
    inputSchema: GetProductRecommendationsInputSchema,
    outputSchema: GetProductRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await productRecommendationsPrompt(input);
    return output!;
  }
);
