import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Astro-Grip Sneakers',
    description: 'Walk on clouds with zero-gravity soles.',
    longDescription: 'The Astro-Grip Sneakers are engineered with cutting-edge, zero-gravity foam that makes you feel like you are walking on air. The breathable mesh upper keeps your feet cool, while the futuristic design ensures you stand out. Perfect for urban explorers and trendsetters.',
    price: 129.99,
    image: 'https://picsum.photos/600/600?random=1',
    category: 'Footwear',
  },
  {
    id: 'prod_002',
    name: 'Quantum-Core Hoodie',
    description: 'A hoodie that adapts to any temperature.',
    longDescription: 'Experience unparalleled comfort with the Quantum-Core Hoodie. Its smart fabric technology adapts to your body temperature, providing warmth when it\'s cold and breathability when it\'s hot. The minimalist design is versatile for any occasion.',
    price: 89.99,
    image: 'https://picsum.photos/600/600?random=2',
    category: 'Apparel',
  },
  {
    id: 'prod_003',
    name: 'Chrono-Shift Watch',
    description: 'A timeless design with a futuristic twist.',
    longDescription: 'The Chrono-Shift Watch blends classic aesthetics with modern technology. Its holographic face can be customized to match your style, while the durable stainless steel body ensures it lasts a lifetime. It\'s more than a watch; it\'s a statement.',
    price: 249.99,
    image: 'https://picsum.photos/600/600?random=3',
    category: 'Accessories',
  },
  {
    id: 'prod_004',
    name: 'Nova-Charge Backpack',
    description: 'Solar-powered to keep your devices charged.',
    longDescription: 'Never run out of battery again with the Nova-Charge Backpack. Integrated solar panels keep your devices powered up on the go. With multiple compartments and a water-resistant exterior, it\'s the ultimate bag for work, travel, and adventure.',
    price: 149.99,
    image: 'https://picsum.photos/600/600?random=4',
    category: 'Gear',
  },
  {
    id: 'prod_005',
    name: 'Echo-Sound Earpods',
    description: 'Crystal-clear audio in a sleek package.',
    longDescription: 'Immerse yourself in sound with Echo-Sound Earpods. Featuring active noise cancellation and a high-fidelity audio driver, they deliver an unmatched listening experience. The ergonomic design provides a secure and comfortable fit for hours of use.',
    price: 179.99,
    image: 'https://picsum.photos/600/600?random=5',
    category: 'Electronics',
  },
  {
    id: 'prod_006',
    name: 'Stealth-Fit Jeans',
    description: 'Comfortable, durable, and stylishly modern.',
    longDescription: 'Redefine your everyday wear with Stealth-Fit Jeans. Made from a premium stretch-denim blend, they offer maximum comfort and flexibility without sacrificing durability. The slim, tailored fit provides a sharp, modern silhouette.',
    price: 79.99,
    image: 'https://picsum.photos/600/600?random=6',
    category: 'Apparel',
  },
  {
    id: 'prod_007',
    name: 'Aura-Glow Lamp',
    description: 'Smart lamp to set the perfect mood.',
    longDescription: 'Transform your space with the Aura-Glow Lamp. With millions of colors and dynamic light scenes, you can create the perfect ambiance for any mood or occasion. Control it with your voice or through our intuitive app.',
    price: 69.99,
    image: 'https://picsum.photos/600/600?random=7',
    category: 'Home',
  },
  {
    id: 'prod_008',
    name: 'Vortex-Cool Bottle',
    description: 'Keeps your drinks cold for 48 hours.',
    longDescription: 'The Vortex-Cool Bottle is a marvel of insulation technology. Its double-walled vacuum design keeps beverages ice-cold for up to 48 hours or hot for 24. The leak-proof lid and rugged exterior make it the perfect companion for any journey.',
    price: 39.99,
    image: 'https://picsum.photos/600/600?random=8',
    category: 'Gear',
  },
  {
    id: 'prod_009',
    name: 'Cyber-Viz Glasses',
    description: 'AR-enabled sunglasses for the modern age.',
    longDescription: 'Step into the future with Cyber-Viz Glasses. These augmented reality sunglasses overlay useful information onto your world, from navigation to notifications. The stylish frames and polarized lenses also protect your eyes from the sun.',
    price: 399.99,
    image: 'https://picsum.photos/600/600?random=9',
    category: 'Electronics',
  },
  {
    id: 'prod_010',
    name: 'Terra-Trek Boots',
    description: 'Conquer any terrain with these all-weather boots.',
    longDescription: 'Built for the toughest conditions, the Terra-Trek Boots are waterproof, breathable, and incredibly durable. The high-traction outsole provides superior grip on any surface, while the cushioned insole ensures all-day comfort. Adventure awaits.',
    price: 199.99,
    image: 'https://picsum.photos/600/600?random=10',
    category: 'Footwear',
  },
];
